### Create User
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "nara@gmail.com",
  "name": "Nara",
  "password": "secret123"
}
### Create User
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "nara@gmail.com",
  "password": "secret123"
}
### Create User
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "notnsa@gmail.com",
  "name": "notnsasss",
  "password": "secret123"
}

###

### Login
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "notnsa@gmail.com",
  "password": "secret123"
}

###
PUT http://localhost:3001/api/users/notnsa@gmail.com
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5vdG5zYUBnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNzgwNzY1MTE3fQ.wNnDzfUrJ2fKIyEYmc7rQdEm5lDWOfuv15l0zjKD2XE

{
"username": "nara"
}
###
POST http://localhost:3001/api/reset
###

### Create Blog (replace TOKEN)
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hcmFAZ21haWwuY29tIiwiaWQiOjIsImlhdCI6MTc4MDgyNTU3OX0.8ZSOFMGxESgoT05h1WktO2wLlGOpQPWQMsthexYc5Mg

{
  "author": "Nara",
  "url": "https://example.com/blog-1",
  "title": "aasasasaaaaa",
  "likes": 0,
  "year": 2023
}
### Create Blog (replace TOKEN)
POST http://localhost:3001/api/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hcmFAZ21haWwuY29tIiwiaWQiOjIsImlhdCI6MTc4MDgyNTU3OX0.8ZSOFMGxESgoT05h1WktO2wLlGOpQPWQMsthexYc5Mg


###

### Get All Blogs
GET http://localhost:3001/api/blogs

###

### Get Blog By ID
GET http://localhost:3001/api/blogs/1

###

### Update Likes
PUT http://localhost:3001/api/blogs/1
Content-Type: application/json

{
  "likes": 10
}

###

### Delete Blog
DELETE http://localhost:3001/api/blogs/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hcmEiLCJpZCI6MSwiaWF0IjoxNzgwNzM5MDAyfQ.ZrgpIyrwR32dL9pWlxWlug1-LWBWKTjyDOLYfHHazmQ